version: '3.1'
services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - N8N_PROTOCOL=https
      - N8N_HOST=45-137-67-204.sslip.io
      - WEBHOOK_URL=https://45-137-67-204.sslip.io
      - N8N_EDITOR_BASE_URL=https://45-137-67-204.sslip.io
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_BASIC_AUTH_EXCLUDE_ENDPOINTS=rest/oauth2-credential/callback,rest/oauth1-credential/callback
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_SECURE_COOKIE=true
    volumes:
      - ./n8n_data:/home/node/.n8n

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - n8n

volumes:
  caddy_data:
  caddy_config:
